#include <stdint.h>
#include "stm32f103x6.h"
#include "i2c.h"

void I2C1_Init(void){

	// ENABLE CLOCK
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN | RCC_APB2ENR_IOPBEN; // AFIO AND GPIO B
	RCC->APB1ENR |= RCC_APB1ENR_I2C1EN; // I2C1

	// CNF = 11 (ALTERNATE FUNCTION OPEN DRAIN) AND MODE = 11 (50MHZ)
	GPIOB->CRL &= ~( GPIO_CRL_CNF7_Msk | GPIO_CRL_MODE7_Msk | GPIO_CRL_CNF6_Msk | GPIO_CRL_MODE6_Msk); // RESET THE BIT
	GPIOB->CRL |= (GPIO_CRL_CNF7 | GPIO_CRL_MODE7 | GPIO_CRL_CNF6 | GPIO_CRL_MODE6); // SET THE BIT

	// RESET OF I2C
	I2C1->CR1 |= I2C_CR1_SWRST;
	I2C1->CR1 &= ~I2C_CR1_SWRST;

	// FREQUENCY [5:0] = 8 FOR 8MHZ
	I2C1->CR2 = 8;

	// CLOCK REGISTER 100KHZ = 40 (STANDARD MODE)
	I2C1->CCR = 40;

	// RISE TIME = 9 (STANDARD MODE)
	I2C1->TRISE = 9;

	// I2C1 PHERIPHERAL ENABLE
	I2C1->CR1 |= I2C_CR1_PE;

}

void I2C1_Start(void){

	// WAIT TILL THE I2C BECOME BUSY
	while(I2C1->SR2 & I2C_SR2_BUSY);

	// GENERATE START CONDITION
	I2C1->CR1 |= I2C_CR1_START;

	// WAIT TILL START CONDITION GENERATED
	while (!(I2C1->SR1 & I2C_SR1_SB));
}


void I2C1_Stop(void){

	// GENERATE STOP CONDITION
	I2C1->CR1 |= I2C_CR1_STOP;
}

void I2C1_WriteAddress(uint8_t address){

	// SENDING ADDRESS
	I2C1->DR = address;

	// WAIT FOR ADDRESS SEND AND ACK RECEIVE
	while (!(I2C1->SR1 & I2C_SR1_ADDR));

	// CLEARING THE FLAG
	(void) I2C1->SR2;
}

void I2C1_WriteData(uint8_t data)
{
	// WAIT TILL THE TX BUFFER IS EMPTY
    while (!(I2C1->SR1 & I2C_SR1_TXE));

    // SENDING DATA
    I2C1->DR = data;

    // WAIT FOR BYTE TRANSFER FINISHER
    while (!(I2C1->SR1 & I2C_SR1_BTF));
}

uint8_t I2C1_ReadData_ACK(void){

	// ENABLE ACK (SAYING WE NEED MORE DATA)
	I2C1->CR1 |= I2C_CR1_ACK;

	// WAIT FOR THE DATA ARRIVAL
	while(!(I2C1->SR1 & I2C_SR1_RXNE));

	// READ AND
	return (uint8_t)I2C1->DR;
}

uint8_t I2C1_ReadData_NACK(void){

	// DISABLE ACK (NACK) FOR LAST DATA
	I2C1->CR1 &= ~I2C_CR1_ACK;

	// GENERATE STOP CONDITION
	I2C1->CR1 |= I2C_CR1_STOP;

	// WAIT FOR THE DATA ARRIVAL
	while(!(I2C1->SR1 & I2C_SR1_RXNE));

	// READ AND RETURN DATA
	return (uint8_t)I2C1->DR;
}
