#include <stdint.h>
#include "stm32f103x6.h"
#include "i2c.h"

void I2C1_Init(void){

	// ENABLE CLOCK
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN | RCC_APB2ENR_IOPBEN; // AFIO AND GPIO B
	RCC->APB1ENR |= RCC_APB1ENR_I2C1EN; // I2C1

	// CNF = 11 (ALTERNATE FUNCTION OPEN DRAIN) AND MODE = 11 (50MHZ)
	GPIOB->CRL = (GPIOB->CRL & ~( GPIO_CRL_CNF7_Msk | GPIO_CRL_MODE7_Msk | GPIO_CRL_CNF6_Msk | GPIO_CRL_MODE6_Msk)) | (GPIO_CRL_CNF7 | GPIO_CRL_MODE7 | GPIO_CRL_CNF6 | GPIO_CRL_MODE6);

	// RESET OF I2C
	I2C1->CR1 |= I2C_CR1_SWRST;
	I2C1->CR1 &= ~I2C_CR1_SWRST;

	// FREQUENCY [5:0] = 8 FOR 8MHZ
	I2C1->CR2 = 8;

	I2C1->CCR = 40;

}

